name: Docker CI

on:
  push:
    branches:
      - "main"
  schedule:
  #          ┌───────────── minute (0 - 59)
  #          │  ┌───────────── hour (0 - 23)
  #          │  │ ┌───────────── day of the month (1 - 31)
  #          │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #          │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #          │  │ │ │ │
  #          │  │ │ │ │
  #          │  │ │ │ │
    - cron: '13 8 * * 0'

jobs:
  docker:
    name: D-LDC CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Apply workaround for sudo bug (https://github.com/multiarch/qemu-user-static/issues/17)
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push - Alpine [1.40.0]
        uses: docker/build-push-action@v5
        with:
          file: ldc/1.40.0/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/alpine-ldc2:1.40.0

      # - name: Build and push - Alpine [master]
      #   uses: docker/build-push-action@v5
      #   with:
      #     file: ldc/master/Dockerfile
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/alpine-ldc2:latest

  opend-ldc:
    name: OpenD-LDC CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Apply workaround for sudo bug (https://github.com/multiarch/qemu-user-static/issues/17)
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push - Alpine-openD [master]
        uses: docker/build-push-action@v5
        with:
          file: opend-ldc/master/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/alpine-opend:latest

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
